import JSZip from 'jszip';
import type { TestSuiteResult } from '../types';

export async function exportTestSuiteZip(suite: TestSuiteResult): Promise<Blob> {
  const zip = new JSZip();
  const rawTitle = suite.scenario.title || 'test_suite';
  const safeName = rawTitle.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '') || 'suite';

  // 1. Playwright Test Spec
  zip.file(`tests/${safeName}.spec.ts`, suite.generatedCode.playwright);

  // 2. Playwright POM
  zip.file(`tests/pages/${safeName}.page.ts`, suite.generatedCode.playwrightPom);

  // 3. Playwright Config
  const playwrightConfig = `import { defineConfig, devices } from '@playwright/test';

/**
 * Think Automation Lab By Rounak - Playwright Automation Configuration
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html'], ['list']],
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
`;
  zip.file('playwright.config.ts', playwrightConfig);

  // 4. Cypress E2E Spec
  zip.file(`cypress/e2e/${safeName}.cy.ts`, suite.generatedCode.cypress);

  // 5. Gherkin Feature File
  zip.file(`features/${safeName}.feature`, suite.generatedCode.gherkin);

  // 6. QA Test Plan Matrix CSV & Markdown
  zip.file(`qa-matrix/${safeName}_test_matrix.csv`, suite.generatedCode.qaMatrixCsv);
  zip.file(`qa-matrix/${safeName}_test_matrix.md`, suite.generatedCode.qaMatrixMarkdown);

  // 7. package.json
  const packageJson = {
    name: `think-automation-lab-${safeName}`,
    version: '1.0.0',
    description: `99%+ Coverage Test Suite for ${suite.scenario.title} by Think Automation Lab By Rounak`,
    scripts: {
      test: 'playwright test',
      'test:ui': 'playwright test --ui',
      'test:headed': 'playwright test --headed',
      'test:report': 'playwright show-report',
      'test:cypress': 'cypress run',
    },
    devDependencies: {
      '@playwright/test': '^1.45.0',
      '@types/node': '^20.0.0',
      typescript: '^5.0.0',
    },
  };
  zip.file('package.json', JSON.stringify(packageJson, null, 2));

  // 8. README.md
  const readmeContent = `# 99%+ Coverage Test Suite: ${suite.scenario.title}
**Generated by Think Automation Lab By Rounak**

## 📊 Suite Breakdown
- **Total Test Cases:** ${suite.totalCases}
- **Happy Path Cases:** ${suite.breakdown.happy_path}
- **Boundary Value Analysis (BVA):** ${suite.breakdown.boundary_value}
- **Equivalence Partitioning:** ${suite.breakdown.equivalence_partition}
- **Negative & Error Handling:** ${suite.breakdown.negative_error}
- **State Transition & Rules:** ${suite.breakdown.state_transition}
- **Security & Resiliency:** ${suite.breakdown.security_edge}
- **Accessibility (A11y):** ${suite.breakdown.accessibility}

---

## 🚀 How to Run Playwright Tests (Beginner Guide)

1. Install dependencies:
   \`\`\`bash
   npm install
   npx playwright install --with-deps
   \`\`\`

2. Run all tests:
   \`\`\`bash
   npx playwright test
   \`\`\`

3. Run in interactive UI mode:
   \`\`\`bash
   npx playwright test --ui
   \`\`\`

4. View visual HTML test report:
   \`\`\`bash
   npx playwright show-report
   \`\`\`
`;
  zip.file('README.md', readmeContent);

  return await zip.generateAsync({
    type: 'blob',
    mimeType: 'application/zip',
  });
}

export function downloadBlob(blob: Blob, filename: string) {
  // Use a File object (not raw Blob) — Chrome uses the File's .name property
  // to determine the download filename when the download attribute is ambiguous.
  const file = new File([blob], filename, { type: blob.type });
  const url = URL.createObjectURL(file);

  const a = document.createElement('a');
  a.style.cssText = 'position:fixed;top:-9999px;left:-9999px;opacity:0;';
  a.setAttribute('download', filename);
  a.href = url;

  // Anchor MUST be in the live DOM before the click fires in Chrome
  document.body.appendChild(a);

  // requestAnimationFrame ensures the browser has painted the element
  // before we trigger the click — fixes Chrome's "blob URL without extension" bug
  requestAnimationFrame(() => {
    a.click(); // single click — no dispatchEvent duplicate

    // Revoke after a generous delay so Chrome finishes reading the blob before cleanup
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 3000);
  });
}

export function downloadTextFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  downloadBlob(blob, filename);
}
